use crate::models::{SkillEdge, SkillGraph, SkillNode};

pub fn generate_cloud_native_skill_graph() -> SkillGraph {
    let nodes = vec![
        SkillNode {
            id: "skill-linux".to_string(),
            name: "Linux Systems & CLI".to_string(),
            slug: "linux-cli".to_string(),
            category: "Foundations".to_string(),
            description: "Linux system administration, file permissions, signals, and bash scripting.".to_string(),
            level: 3,
            xp: 350,
            icon: "Terminal".to_string(),
            prerequisites: vec![],
        },
        SkillNode {
            id: "skill-containers".to_string(),
            name: "OCI Containers & Podman".to_string(),
            slug: "containers".to_string(),
            category: "Foundations".to_string(),
            description: "Linux namespaces, cgroups, rootless containers, and image builds.".to_string(),
            level: 2,
            xp: 250,
            icon: "Container".to_string(),
            prerequisites: vec!["skill-linux".to_string()],
        },
        SkillNode {
            id: "skill-k8s-workloads".to_string(),
            name: "Kubernetes Workloads".to_string(),
            slug: "k8s-workloads".to_string(),
            category: "Kubernetes Core".to_string(),
            description: "Pods, Deployments, StatefulSets, DaemonSets, and Jobs.".to_string(),
            level: 4,
            xp: 600,
            icon: "Boxes".to_string(),
            prerequisites: vec!["skill-containers".to_string()],
        },
        SkillNode {
            id: "skill-networking".to_string(),
            name: "Kubernetes Networking".to_string(),
            slug: "k8s-networking".to_string(),
            category: "Networking".to_string(),
            description: "Services, Endpoints, CNI plugins, CoreDNS, and Ingress routing.".to_string(),
            level: 3,
            xp: 450,
            icon: "Network".to_string(),
            prerequisites: vec!["skill-k8s-workloads".to_string()],
        },
        SkillNode {
            id: "skill-gitops".to_string(),
            name: "GitOps & Argo CD".to_string(),
            slug: "gitops-argocd".to_string(),
            category: "GitOps".to_string(),
            description: "Continuous delivery with Argo CD, drift detection, and auto-sync.".to_string(),
            level: 3,
            xp: 400,
            icon: "GitBranch".to_string(),
            prerequisites: vec!["skill-k8s-workloads".to_string()],
        },
        SkillNode {
            id: "skill-service-mesh".to_string(),
            name: "Istio Service Mesh".to_string(),
            slug: "service-mesh".to_string(),
            category: "Service Mesh".to_string(),
            description: "Envoy sidecars, traffic shifting, mTLS, and circuit breakers.".to_string(),
            level: 2,
            xp: 300,
            icon: "Layers".to_string(),
            prerequisites: vec!["skill-networking".to_string()],
        },
        SkillNode {
            id: "skill-observability".to_string(),
            name: "OpenTelemetry & Prometheus".to_string(),
            slug: "observability".to_string(),
            category: "Observability".to_string(),
            description: "Distributed tracing, PromQL metrics queries, and Grafana dashboards.".to_string(),
            level: 3,
            xp: 500,
            icon: "Activity".to_string(),
            prerequisites: vec!["skill-k8s-workloads".to_string()],
        },
        SkillNode {
            id: "skill-incidents".to_string(),
            name: "Production Incident Response".to_string(),
            slug: "incidents".to_string(),
            category: "SRE".to_string(),
            description: "Diagnose and fix live production outages under pressure.".to_string(),
            level: 2,
            xp: 350,
            icon: "AlertTriangle".to_string(),
            prerequisites: vec!["skill-observability".to_string(), "skill-networking".to_string()],
        },
    ];

    let edges = vec![
        SkillEdge { source: "skill-linux".to_string(), target: "skill-containers".to_string() },
        SkillEdge { source: "skill-containers".to_string(), target: "skill-k8s-workloads".to_string() },
        SkillEdge { source: "skill-k8s-workloads".to_string(), target: "skill-networking".to_string() },
        SkillEdge { source: "skill-k8s-workloads".to_string(), target: "skill-gitops".to_string() },
        SkillEdge { source: "skill-networking".to_string(), target: "skill-service-mesh".to_string() },
        SkillEdge { source: "skill-k8s-workloads".to_string(), target: "skill-observability".to_string() },
        SkillEdge { source: "skill-observability".to_string(), target: "skill-incidents".to_string() },
        SkillEdge { source: "skill-networking".to_string(), target: "skill-incidents".to_string() },
    ];

    SkillGraph { nodes, edges }
}
