use crate::models::{LessonDetail, TrackSummary};

pub fn get_default_tracks() -> Vec<TrackSummary> {
    vec![
        TrackSummary {
            id: "track-foundations".to_string(),
            slug: "foundations".to_string(),
            title: "Cloud-Native & Linux Foundations".to_string(),
            description: "Linux systems engineering, shell scripting, namespaces, cgroups, and OCI container fundamentals with Docker and Podman.".to_string(),
            icon: "Terminal".to_string(),
            difficulty: "beginner".to_string(),
            order: 1,
            total_lessons: 15,
            total_xp: 1500,
        },
        TrackSummary {
            id: "track-kubernetes".to_string(),
            slug: "kubernetes".to_string(),
            title: "Kubernetes Core Architecture & Workloads".to_string(),
            description: "Master Pods, Deployments, Services, ConfigMaps, Secrets, Storage, and Declarative manifests in real Kubernetes clusters.".to_string(),
            icon: "Boxes".to_string(),
            difficulty: "beginner".to_string(),
            order: 2,
            total_lessons: 20,
            total_xp: 2500,
        },
        TrackSummary {
            id: "track-k8s-admin".to_string(),
            slug: "k8s-admin".to_string(),
            title: "Cluster Administration & etcd Operations".to_string(),
            description: "Bootstrap clusters with kubeadm, handle control-plane high availability, etcd snapshots and disaster recovery, and node maintenance.".to_string(),
            icon: "Server".to_string(),
            difficulty: "intermediate".to_string(),
            order: 3,
            total_lessons: 12,
            total_xp: 1800,
        },
        TrackSummary {
            id: "track-networking".to_string(),
            slug: "networking".to_string(),
            title: "Cloud-Native Networking, CNI & Gateway API".to_string(),
            description: "Deep dive into CNI plugins (Calico/Cilium), CoreDNS resolution, Ingress Controllers, eBPF data planes, and Kubernetes Gateway API.".to_string(),
            icon: "Network".to_string(),
            difficulty: "intermediate".to_string(),
            order: 4,
            total_lessons: 14,
            total_xp: 2100,
        },
        TrackSummary {
            id: "track-security".to_string(),
            slug: "security".to_string(),
            title: "Kubernetes Security, RBAC & Policy Hardening".to_string(),
            description: "Implement RBAC, Pod Security Standards, NetworkPolicies, Seccomp profiles, image vulnerability scanning, and CIS benchmarks.".to_string(),
            icon: "ShieldCheck".to_string(),
            difficulty: "intermediate".to_string(),
            order: 5,
            total_lessons: 15,
            total_xp: 2250,
        },
        TrackSummary {
            id: "track-helm".to_string(),
            slug: "helm".to_string(),
            title: "Packaging with Helm & Kustomize".to_string(),
            description: "Author production Helm charts, manage chart repositories, leverage Go templates, and apply dry Kustomize overlays.".to_string(),
            icon: "Package".to_string(),
            difficulty: "intermediate".to_string(),
            order: 6,
            total_lessons: 10,
            total_xp: 1500,
        },
        TrackSummary {
            id: "track-gitops".to_string(),
            slug: "gitops".to_string(),
            title: "GitOps & Continuous Delivery with Argo CD".to_string(),
            description: "Implement declarative GitOps workflows, App-of-Apps pattern, automated sync policies, drift detection, and automated rollbacks.".to_string(),
            icon: "GitBranch".to_string(),
            difficulty: "intermediate".to_string(),
            order: 7,
            total_lessons: 12,
            total_xp: 2000,
        },
        TrackSummary {
            id: "track-observability".to_string(),
            slug: "observability".to_string(),
            title: "OpenTelemetry, Prometheus & Grafana".to_string(),
            description: "End-to-end distributed tracing with OpenTelemetry, metric collection with Prometheus, PromQL alerting, and Grafana dashboarding.".to_string(),
            icon: "Activity".to_string(),
            difficulty: "advanced".to_string(),
            order: 8,
            total_lessons: 15,
            total_xp: 2400,
        },
        TrackSummary {
            id: "track-service-mesh".to_string(),
            slug: "service-mesh".to_string(),
            title: "Service Mesh with Istio & Envoy Proxy".to_string(),
            description: "Traffic shifting, canary releases, mutual TLS (mTLS), fault injection, rate limiting, and Envoy sidecar telemetry.".to_string(),
            icon: "Layers".to_string(),
            difficulty: "advanced".to_string(),
            order: 9,
            total_lessons: 14,
            total_xp: 2300,
        },
        TrackSummary {
            id: "track-sre".to_string(),
            slug: "sre".to_string(),
            title: "Site Reliability Engineering & SLOs".to_string(),
            description: "Define meaningful SLIs/SLOs, error budget burn rates, alerting thresholds, HPA/VPA autoscaling, and capacity planning.".to_string(),
            icon: "Gauge".to_string(),
            difficulty: "advanced".to_string(),
            order: 10,
            total_lessons: 12,
            total_xp: 2000,
        },
        TrackSummary {
            id: "track-platform-eng".to_string(),
            slug: "platform-eng".to_string(),
            title: "Platform Engineering & Multi-Cluster".to_string(),
            description: "Build Internal Developer Platforms (IDPs), write Kubernetes Operators and CRDs in Go/Rust, and manage multi-cluster fleets.".to_string(),
            icon: "Cpu".to_string(),
            difficulty: "expert".to_string(),
            order: 11,
            total_lessons: 10,
            total_xp: 2500,
        },
        TrackSummary {
            id: "track-incidents".to_string(),
            slug: "incidents".to_string(),
            title: "Production Incident Response & Chaos".to_string(),
            description: "Real-world break-fix simulations: debug crashloops, network partitions, DNS degradation, expired certs, and GitOps sync deadlocks.".to_string(),
            icon: "AlertTriangle".to_string(),
            difficulty: "expert".to_string(),
            order: 12,
            total_lessons: 10,
            total_xp: 3000,
        },
    ]
}

pub fn get_default_lessons() -> Vec<LessonDetail> {
    vec![
        LessonDetail {
            id: "k8s-pod-architecture".to_string(),
            track_slug: "kubernetes".to_string(),
            title: "Understanding the Pod: The Atomic Unit of Kubernetes".to_string(),
            slug: "understanding-pods".to_string(),
            order: 1,
            duration_minutes: 15,
            xp: 150,
            summary: "Learn why Kubernetes uses Pods instead of bare containers, how shared network namespaces and volumes work, and how the pause container coordinates lifecycle.".to_string(),
            content_markdown: "# Understanding Pods: The Fundamental Primitive\n\nIn Kubernetes, you never deploy individual containers directly. Instead, you deploy **Pods**. A Pod is the smallest deployable compute unit that you can create and manage in Kubernetes.\n\n## The Role of the Pause Container\n\nEvery Pod includes an infrastructure container called `pause` that holds the network namespace open...".to_string(),
            concepts: vec!["pod".to_string(), "pause-container".to_string(), "network-namespace".to_string()],
            prerequisites: vec![],
            associated_lab_id: Some("k8s-pod-basics".to_string()),
            associated_quiz_id: Some("quiz-k8s-pods".to_string()),
        },
        LessonDetail {
            id: "k8s-deployments-rollouts".to_string(),
            track_slug: "kubernetes".to_string(),
            title: "Deployments, ReplicaSets & Zero-Downtime Rollouts".to_string(),
            slug: "deployments-and-rollouts".to_string(),
            order: 2,
            duration_minutes: 20,
            xp: 200,
            summary: "Master declarative workload updates with Deployments, RollingUpdate strategies, revision history, and instant rollbacks.".to_string(),
            content_markdown: "# Deployments & Rolling Updates\n\nA **Deployment** provides declarative updates for Pods and ReplicaSets...".to_string(),
            concepts: vec!["deployment".to_string(), "replicaset".to_string(), "rolling-update".to_string()],
            prerequisites: vec!["k8s-pod-architecture".to_string()],
            associated_lab_id: Some("k8s-deployments-scaling".to_string()),
            associated_quiz_id: Some("quiz-k8s-deployments".to_string()),
        },
    ]
}
