// Generated by scripts/generate_authoritative_curriculum.py - DO NOT EDIT DIRECTLY
import 'dart:convert';

class MobileQuestion {
  final String id;
  final String prompt;
  final List<String> options;
  final int correctIndex;
  final String explanation;
  final String category;

  const MobileQuestion({
    required this.id,
    required this.prompt,
    required this.options,
    required this.correctIndex,
    required this.explanation,
    this.category = 'concept',
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'prompt': prompt,
    'options': options,
    'correctIndex': correctIndex,
    'explanation': explanation,
    'category': category,
  };

  factory MobileQuestion.fromJson(Map<String, dynamic> json) => MobileQuestion(
    id: json['id'] as String,
    prompt: json['prompt'] as String,
    options: List<String>.from(json['options'] as List),
    correctIndex: json['correctIndex'] as int,
    explanation: json['explanation'] as String,
    category: json['category'] as String? ?? 'concept',
  );
}

class MobileLessonQuiz {
  final String id;
  final String lessonId;
  final String trackSlug;
  final String title;
  final String description;
  final int questionCount;
  final List<MobileQuestion> questions;
  final int passingScore;
  final int xpReward;

  const MobileLessonQuiz({
    required this.id,
    required this.lessonId,
    required this.trackSlug,
    required this.title,
    required this.description,
    required this.questionCount,
    required this.questions,
    this.passingScore = 80,
    this.xpReward = 75,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'lessonId': lessonId,
    'trackSlug': trackSlug,
    'title': title,
    'description': description,
    'questionCount': questionCount,
    'questions': questions.map((q) => q.toJson()).toList(),
    'passingScore': passingScore,
    'xpReward': xpReward,
  };

  factory MobileLessonQuiz.fromJson(Map<String, dynamic> json) => MobileLessonQuiz(
    id: json['id'] as String,
    lessonId: json['lessonId'] as String,
    trackSlug: json['trackSlug'] as String,
    title: json['title'] as String,
    description: json['description'] as String,
    questionCount: json['questionCount'] as int? ?? (json['questions'] as List).length,
    questions: (json['questions'] as List).map((q) => MobileQuestion.fromJson(q as Map<String, dynamic>)).toList(),
    passingScore: json['passingScore'] as int? ?? 80,
    xpReward: json['xpReward'] as int? ?? 75,
  );
}

class MobileLesson {
  final String id;
  final String moduleId;
  final String trackSlug;
  final String title;
  final String slug;
  final int order;
  final int durationMinutes;
  final int xp;
  final String summary;
  final String contentMarkdown;
  final List<String> concepts;
  final List<String> prerequisites;
  final String associatedLabId;
  final String associatedQuizId;
  final List<String> commonMistakes;
  final String productionGuidance;
  final String diagram;

  const MobileLesson({
    required this.id,
    required this.moduleId,
    required this.trackSlug,
    required this.title,
    required this.slug,
    required this.order,
    required this.durationMinutes,
    required this.xp,
    required this.summary,
    required this.contentMarkdown,
    required this.concepts,
    required this.prerequisites,
    required this.associatedLabId,
    required this.associatedQuizId,
    required this.commonMistakes,
    required this.productionGuidance,
    this.diagram = '',
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'moduleId': moduleId,
    'trackSlug': trackSlug,
    'title': title,
    'slug': slug,
    'order': order,
    'durationMinutes': durationMinutes,
    'xp': xp,
    'summary': summary,
    'contentMarkdown': contentMarkdown,
    'concepts': concepts,
    'prerequisites': prerequisites,
    'associatedLabId': associatedLabId,
    'associatedQuizId': associatedQuizId,
    'commonMistakes': commonMistakes,
    'productionGuidance': productionGuidance,
    'diagram': diagram,
  };

  factory MobileLesson.fromJson(Map<String, dynamic> json) => MobileLesson(
    id: json['id'] as String,
    moduleId: json['moduleId'] as String,
    trackSlug: json['trackSlug'] as String,
    title: json['title'] as String,
    slug: json['slug'] as String,
    order: json['order'] as int,
    durationMinutes: json['durationMinutes'] as int,
    xp: json['xp'] as int,
    summary: json['summary'] as String,
    contentMarkdown: json['contentMarkdown'] as String,
    concepts: List<String>.from(json['concepts'] as List),
    prerequisites: List<String>.from(json['prerequisites'] as List),
    associatedLabId: json['associatedLabId'] as String,
    associatedQuizId: json['associatedQuizId'] as String,
    commonMistakes: List<String>.from(json['commonMistakes'] as List),
    productionGuidance: json['productionGuidance'] as String,
    diagram: json['diagram'] as String? ?? '',
  );
}

class MobileModule {
  final String id;
  final String trackId;
  final String title;
  final String slug;
  final int order;
  final String description;
  final List<MobileLesson> lessons;

  const MobileModule({
    required this.id,
    required this.trackId,
    required this.title,
    required this.slug,
    required this.order,
    required this.description,
    required this.lessons,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'trackId': trackId,
    'title': title,
    'slug': slug,
    'order': order,
    'description': description,
    'lessons': lessons.map((l) => l.toJson()).toList(),
  };

  factory MobileModule.fromJson(Map<String, dynamic> json) => MobileModule(
    id: json['id'] as String,
    trackId: json['trackId'] as String,
    title: json['title'] as String,
    slug: json['slug'] as String,
    order: json['order'] as int,
    description: json['description'] as String,
    lessons: (json['lessons'] as List).map((l) => MobileLesson.fromJson(l as Map<String, dynamic>)).toList(),
  );
}

class MobileTrack {
  final String id;
  final String slug;
  final String title;
  final String description;
  final String icon;
  final String color;
  final String difficulty;
  final int order;
  final int totalLessons;
  final int totalXp;
  final List<MobileModule> modules;

  String get colorHex => color;

  const MobileTrack({
    required this.id,
    required this.slug,
    required this.title,
    required this.description,
    required this.icon,
    required this.color,
    required this.difficulty,
    required this.order,
    required this.totalLessons,
    required this.totalXp,
    required this.modules,
  });

  Map<String, dynamic> toJson() => {
    'id': id,
    'slug': slug,
    'title': title,
    'description': description,
    'icon': icon,
    'color': color,
    'difficulty': difficulty,
    'order': order,
    'totalLessons': totalLessons,
    'totalXp': totalXp,
    'modules': modules.map((m) => m.toJson()).toList(),
  };

  factory MobileTrack.fromJson(Map<String, dynamic> json) => MobileTrack(
    id: json['id'] as String,
    slug: json['slug'] as String,
    title: json['title'] as String,
    description: json['description'] as String,
    icon: json['icon'] as String,
    color: json['color'] as String,
    difficulty: json['difficulty'] as String,
    order: json['order'] as int,
    totalLessons: json['totalLessons'] as int,
    totalXp: json['totalXp'] as int,
    modules: (json['modules'] as List).map((m) => MobileModule.fromJson(m as Map<String, dynamic>)).toList(),
  );
}

class CurriculumRepository {
  static List<MobileTrack> tracks = [];
  static Map<String, MobileLessonQuiz> quizzes = {};

  static void initializeFromJson(String rawJson) {
    final data = jsonDecode(rawJson) as Map<String, dynamic>;
    final trackList = (data['tracks'] as List)
        .map((t) => MobileTrack.fromJson(t as Map<String, dynamic>))
        .toList();
    tracks = trackList;

    final quizMap = (data['quizzes'] as Map<String, dynamic>).map(
      (k, v) => MapEntry(k, MobileLessonQuiz.fromJson(v as Map<String, dynamic>)),
    );
    quizzes = quizMap;
  }

  static MobileTrack? getTrackBySlug(String slug) {
    try {
      return tracks.firstWhere((t) => t.slug == slug);
    } catch (_) {
      return null;
    }
  }

  static MobileLesson? getLesson(String trackSlug, String lessonSlug) {
    final track = getTrackBySlug(trackSlug);
    if (track == null) return null;
    for (final mod in track.modules) {
      for (final l in mod.lessons) {
        if (l.slug == lessonSlug || l.id == lessonSlug || l.associatedLabId == lessonSlug) {
          return l;
        }
      }
    }
    return null;
  }

  static MobileLessonQuiz? getQuizForLesson(String lessonId) {
    final cleanId = lessonId.replaceFirst('les-', '');
    return quizzes['quiz-$cleanId'] ??
        quizzes.values.cast<MobileLessonQuiz?>().firstWhere(
              (q) => q?.lessonId == lessonId,
              orElse: () => null,
            );
  }

  static MobileLessonQuiz? getQuizById(String quizId) {
    return quizzes[quizId];
  }
}
