import { Track } from '@kubelab/shared-types';

export const TRACKS: Track[] = [
  {
    id: 'track-foundations',
    slug: 'foundations',
    title: 'Cloud-Native & Linux Foundations',
    description: 'Linux systems engineering, shell scripting, namespaces, cgroups, and OCI container fundamentals with Docker and Podman.',
    icon: 'Terminal',
    difficulty: 'beginner',
    order: 1,
    totalLessons: 15,
    totalXp: 1500,
    modules: [],
  },
  {
    id: 'track-kubernetes',
    slug: 'kubernetes',
    title: 'Kubernetes Core Architecture & Workloads',
    description: 'Master Pods, Deployments, Services, ConfigMaps, Secrets, Storage, and Declarative manifests in real Kubernetes clusters.',
    icon: 'Boxes',
    difficulty: 'beginner',
    order: 2,
    totalLessons: 20,
    totalXp: 2500,
    modules: [],
  },
  {
    id: 'track-k8s-admin',
    slug: 'k8s-admin',
    title: 'Cluster Administration & etcd Operations',
    description: 'Bootstrap clusters with kubeadm, handle control-plane high availability, etcd snapshots and disaster recovery, and node maintenance.',
    icon: 'Server',
    difficulty: 'intermediate',
    order: 3,
    totalLessons: 12,
    totalXp: 1800,
    modules: [],
  },
  {
    id: 'track-networking',
    slug: 'networking',
    title: 'Cloud-Native Networking, CNI & Gateway API',
    description: 'Deep dive into CNI plugins (Calico/Cilium), CoreDNS resolution, Ingress Controllers, eBPF data planes, and Kubernetes Gateway API.',
    icon: 'Network',
    difficulty: 'intermediate',
    order: 4,
    totalLessons: 14,
    totalXp: 2100,
    modules: [],
  },
  {
    id: 'track-security',
    slug: 'security',
    title: 'Kubernetes Security, RBAC & Policy Hardening',
    description: 'Implement RBAC, Pod Security Standards, NetworkPolicies, Seccomp profiles, image vulnerability scanning, and CIS benchmarks.',
    icon: 'ShieldCheck',
    difficulty: 'intermediate',
    order: 5,
    totalLessons: 15,
    totalXp: 2250,
    modules: [],
  },
  {
    id: 'track-helm',
    slug: 'helm',
    title: 'Packaging with Helm & Kustomize',
    description: 'Author production Helm charts, manage chart repositories, leverage Go templates, and apply dry Kustomize overlays.',
    icon: 'Package',
    difficulty: 'intermediate',
    order: 6,
    totalLessons: 10,
    totalXp: 1500,
    modules: [],
  },
  {
    id: 'track-gitops',
    slug: 'gitops',
    title: 'GitOps & Continuous Delivery with Argo CD',
    description: 'Implement declarative GitOps workflows, App-of-Apps pattern, automated sync policies, drift detection, and automated rollbacks.',
    icon: 'GitBranch',
    difficulty: 'intermediate',
    order: 7,
    totalLessons: 12,
    totalXp: 2000,
    modules: [],
  },
  {
    id: 'track-observability',
    slug: 'observability',
    title: 'OpenTelemetry, Prometheus & Grafana',
    description: 'End-to-end distributed tracing with OpenTelemetry, metric collection with Prometheus, PromQL alerting, and Grafana dashboarding.',
    icon: 'Activity',
    difficulty: 'advanced',
    order: 8,
    totalLessons: 15,
    totalXp: 2400,
    modules: [],
  },
  {
    id: 'track-service-mesh',
    slug: 'service-mesh',
    title: 'Service Mesh with Istio & Envoy Proxy',
    description: 'Traffic shifting, canary releases, mutual TLS (mTLS), fault injection, rate limiting, and Envoy sidecar telemetry.',
    icon: 'Layers',
    difficulty: 'advanced',
    order: 9,
    totalLessons: 14,
    totalXp: 2300,
    modules: [],
  },
  {
    id: 'track-sre',
    slug: 'sre',
    title: 'Site Reliability Engineering & SLOs',
    description: 'Define meaningful SLIs/SLOs, error budget burn rates, alerting thresholds, HPA/VPA autoscaling, and capacity planning.',
    icon: 'Gauge',
    difficulty: 'advanced',
    order: 10,
    totalLessons: 12,
    totalXp: 2000,
    modules: [],
  },
  {
    id: 'track-platform-eng',
    slug: 'platform-eng',
    title: 'Platform Engineering & Multi-Cluster',
    description: 'Build Internal Developer Platforms (IDPs), write Kubernetes Operators and CRDs in Go/Rust, and manage multi-cluster fleets.',
    icon: 'Cpu',
    difficulty: 'expert',
    order: 11,
    totalLessons: 10,
    totalXp: 2500,
    modules: [],
  },
  {
    id: 'track-incidents',
    slug: 'incidents',
    title: 'Production Incident Response & Chaos',
    description: 'Real-world break-fix simulations: debug crashloops, network partitions, DNS degradation, expired certs, and GitOps sync deadlocks.',
    icon: 'AlertTriangle',
    difficulty: 'expert',
    order: 12,
    totalLessons: 10,
    totalXp: 3000,
    modules: [],
  },
];
